# Generated by Django 4.0 on 2022-03-01 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('created_date', models.DateField()),
                ('due_date', models.DateField()),
                ('category_id', models.ForeignKey(default='personal', on_delete=django.db.models.deletion.CASCADE, to='todoapp.category')),
            ],
            options={
                'db_table': 'todolist',
            },
        ),
    ]
